EXPERIMENT_NAME: 'cover12/ours'
INPUT:
  NUM_WORKERS: 4
  VOXELIZE: True
  VOXEL_GRID_SHAPE: [48, 96, 32]
  MIN_CLOUD_VALUES: [-0.86, -1.18, -0.46]
  VOXEL_GRID_SIZE: [1.71, 2.36, 0.67]
  NORMALIZE_OUTPUT: True
  ROTATION_DEGREE: 20.
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE_TEST: 16
  BATCH_SIZE_TRAIN: 16
  LR_MILESTONES: [60, 100]
  LR_GAMMA: 0.1
  NUM_EPOCHS: 120
  USE_AMP: True
SLP_DATASET:
  COVER_CONDITION: 'cover12'
  VAL_SPLIT: 'dana'
  POSITION: 'all'