EXPERIMENT_NAME: 'cover12/baseline_bps'
MODEL:
  ARCHITECTURE: 'BPS'
  BPS:
    NUM_BASIS_POINTS: 2048
    SEED: 15
    RADIUS: 1.2427
INPUT:
  NUM_POINTS: 2048
  NORMALIZE_OUTPUT: False
  NUM_WORKERS: 4
  VOXELIZE: False
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE_TEST: 16
  BATCH_SIZE_TRAIN: 16
  LR_MILESTONES: [60, 100]
  LR_GAMMA: 0.1
  NUM_EPOCHS: 120
SLP_DATASET:
  COVER_CONDITION: 'cover12'
  VAL_SPLIT: 'dana'
  POSITION: 'all'