EXPERIMENT_NAME: 'cover12/baseline_pointnet'
MODEL:
  ARCHITECTURE: 'PointNet'
INPUT:
  NUM_WORKERS: 4
  VOXELIZE: False
  NORMALIZE_OUTPUT: True
  NUM_POINTS: 2048
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE_TEST: 16
  BATCH_SIZE_TRAIN: 16
  LR_MILESTONES: [60, 100]
  LR_GAMMA: 0.1
  NUM_EPOCHS: 120
SLP_DATASET:
  COVER_CONDITION: 'cover12'
  VAL_SPLIT: 'dana'
  POSITION: 'all'